### ISSUE TITLE
NPC minecart kidnapping

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Mobzy#36]
Although NPCs have movement disabled by overriding those functions, we forgot to disable picking them up into minecarts.

We should figure out what method corresponds to getting picked up into minecarts and override it to do nothing. Ideally we'd actually have components for disabling movement or minecart pickup, though they would likely have to use events, and I'm not too sure that we can consistently catch every use case that way. 

We could also override these methods in MobBase to check whether the component is present and prevent it from triggering if it isn't.

**Comment by pixelfac** [comment]
I submitted prs https://github.com/MineInAbyss/Mobzy/pull/37 and https://github.com/MineInAbyss/server-config/pull/14 to cover this issue

**Comment by Boy0000** [comment]
Merged with #37
