### ISSUE TITLE
Low movementspeed doesnt trigger model change

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#47]
If the movement speed is below 0.2 (default of a zombie?) the model wont go onto the next model. Probably because it still thinks the zombie is standing or just not walking.

Kakatsumuri has 0.1
Kakatsumuri2 has 0.2
https://streamable.com/e9ngah

**Comment by 0ffz** [comment]
Is this issue still a thing @Boy0000?

**Comment by Boy0000** [comment]
Afaik yes
