### ISSUE TITLE
Add "should ignore armor" boolean to !<geary:deal_damage>

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#53]

**Comment by 0ffz** [comment]
If anyone wants to implement this, call it `ignoreArmor` and default to false

**Comment by pixelfac** [comment]
Do I need to also implement the system for ignoring armor, or just make the bool that basically does nothing

**Comment by Norazan** [comment]
> Do I need to also implement the system for ignoring armor, or just make the bool that basically does nothing

Also implement it. For a simple way to do this, just calling the bukkit `Entity.damage()` function takes armor into account. The code thats written there right now sets the HP directly, essentially ignoring armor.

**Comment by pixelfac** [comment]
I'm trying to implement the logic, but IntelliJ keeps giving me `inferred type is Unit but Double was expected` at bukkit.damage()
```kotlin
val bukkit = entity.toBukkit<LivingEntity>() ?: return false
        val ignoreArmor = false
        bukkit.health = if (ignoreArmor) (bukkit.health - damage.randomOrMin()).coerceAtLeast(minHealth) else bukkit.damage(damage.randomOrMin());
        return true
```

**Comment by Norazan** [comment]
`bukkit.damage()` doesn't return a health value, its a void function that deals damage to the target

**Comment by pixelfac** [comment]
ez fix
https://github.com/MineInAbyss/Geary/pull/15
