### ISSUE TITLE
Mobs do not pathfind over rails or tiles.

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#70]
This seems to be a "feature" in Vanilla MC aswell. Hostile mobs should definetly be able to pathfind above them, passive mobs perhaps not

**Comment by 0ffz** [comment]
We're going to be working on our own AI system which would fix this. Even if that doesn't go through this isn't up to us to handle as it's a Minecraft problem, as such I'm closing this.
