### ISSUE TITLE
Right click damages mobs

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#80]
On occasions right clicking a mob can damage them if no other event is fired.
If shift rightclicked with nothing but the hand, it will damage mobs.
This goes for both Custom and vanilla ones.

Probably because of the tracing stuff for custom mob hitboxes?

![Screen Recording 2021-10-20 at 1 34 10 p m](https://user-images.githubusercontent.com/62521371/138085523-02977260-e3e2-4a21-b803-8278f5208432.gif)
.

**Comment by Boy0000** [comment]
https://www.spigotmc.org/threads/tracking-when-entity-gets-damaged-caused-by-playerinteractatentity-event.528813/

**Comment by 0ffz** [comment]
Should be fixed with the new armor stand packets
