### ISSUE TITLE
Consider making mobs despawn when far away

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#85]
Mobcap usually tips of at around 2000 rn but players seemingly have trouble actively finding them.

Consider making flying and passive mobs atleast despawn to make them not be stuck in large areas of layer 4 and 5 thus taking up the mobcap

**Comment by 0ffz** [comment]
Iirc you should be able to change this with a component. I assume a better default is no despawn then add a component to make things despawn
